Bump up task lib patch version to 3.2.1
microsoft/azure-pipelines-task-lib pull request #837
Opened 2022-05-16 15:42 UTC by SvetlanaMaliugina

#### Description: ####
We need to bump up the task lib version to publish recent changes

#### Changes: ####

Updated package patch version in ```node/package.json``` and ```package-lock.json``` files

2022-05-16 15:44 UTC, KonstantinTyukalov approved these changes

2022-05-16 16:01 UTC, AndreyIvanov42 approved these changes

2022-05-16 16:06 UTC, anatolybolshakov approved these changes

2022-05-16 19:49 UTC, AndreyIvanov42 requested changes
There are no changes in the PR except for increasing the version

2022-05-17 10:35 UTC, stalehard approved these changes

2022-05-17 10:36 UTC, AndreyIvanov42 approved these changes

2022-05-17 10:48 UTC, mmrazik approved these changes

2022-05-17 10:50 UTC, merged